name: dartros
description: A Dart implementation of a ROS 1 Client Library
version: 0.0.5+4
repository: https://github.com/TimWhiting/dartros

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  actionlib_msgs: ^0.0.3+2
  buffer: ^1.0.6
  collection: ^1.14.13
  dartx: ^0.5.0
  freezed_annotation: ">0.11.0 <1.0.0"
  http: ^0.12.1
  logger: ^0.9.1
  meta: ^1.2.4
  path: ^1.6.0
  rosgraph_msgs: ^0.0.3
  rxdart: ^0.25.0
  std_msgs: ^0.0.3
  string_validator: ^0.1.4
  xml: ^4.1.0
  xml_rpc: ^0.3.0

dev_dependencies:
  abide: any
  async: any
  build_runner: any
  derry: any
  freezed: any
  pedantic: ^1.8.0
  sensor_msgs: ^0.0.3
  test: ^1.6.0

scripts:
  gen: pub run build_runner build --delete-conflicting-outputs
  genw: pub run build_runner watch --delete-conflicting-outputs
