name: dartros
description: A dart implementation of a ROS 1 Client Library
version: 0.0.1
# homepage: https://www.example.com

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  path: ^1.6.0
  logger: ^0.9.1
  dartx: any
  buffer: any
  meta: any
  freezed_annotation: any
  xml_rpc: ^0.3.0
  # reflectable: any
  string_validator: ^0.1.4
  rxdart: any

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
  freezed: any
  build_runner: any
