name: dartros
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  path: ^1.6.0
  logger: ^0.9.1
  dartx: any
  buffer: any
  meta: any
  xml_rpc:
    git:
      url: git@github.com:TimWhiting/dart-xmlrpc.git
      ref: server

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
