name: Test dartros


on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    container:
      image: osrf/ros:melodic-desktop
    
    steps:
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt-get install apt-transport-https wget
        sudo sh -c 'wget -qO- https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -'
        sudo sh -c 'wget -qO- https://storage.googleapis.com/download.dartlang.org/linux/debian/dart_stable.list > /etc/apt/sources.list.d/dart_stable.list'
        sudo apt-get update
        sudo apt-get install dart
    - name: Clone things
      run: echo 'HELLO'

    
