name: Test dartros


on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    container:
      image: google/dart:latest

    steps:
    - uses: actions/checkout@v2
    - uses: ros-tooling/setup-ros@0.0.25
      with:
        required-ros-distributions: melodic
    - uses: ros-tooling/action-ros-ci@0.0.18
      with:
        package-name: my_package
        target-ros1-distro: melodic
        vcs-repo-file-url: /deps.repos